const fs = require('fs');

const languages = [
  'English', 'Hindi (हिंदी)', 'Hinglish', 'Bengali (বাংলা)', 
  'Telugu (తెలుగు)', 'Marathi (मराठी)', 'Tamil (தமிழ்)', 
  'Gujarati (ગુજરાતી)', 'Kannada (ಕನ್ನಡ)'
];

const dataKeys = {
  // Topics Titles
  'Election Process': ['Election Process', 'चुनाव प्रक्रिया', 'Election Process', 'নির্বাচন প্রক্রিয়া', 'ఎన్నికల ప్రక్రియ', 'निवडणूक प्रक्रिया', 'தேர்தல் செயல்முறை', 'ચૂંટણી પ્રક્રિયા', 'ಚುನಾವಣಾ ಪ್ರಕ್ರಿಯೆ'],
  'Voter Registration': ['Voter Registration', 'मतदाता पंजीकरण', 'Voter Registration', 'ভোটার নিবন্ধন', 'ఓటరు నమోదు', 'मतदार नोंदणी', 'வாக்காளர் பதிவு', 'મતદાર નોંધણી', 'ಮತದಾರರ ನೋಂದಣಿ'],
  'Voting Day': ['Voting Day', 'मतदान का दिन', 'Voting Day', 'ভোটের দিন', 'పోలింగ్ రోజు', 'मतदानाचा दिवस', 'வாக்குப்பதிவு நாள்', 'મતદાનનો દિવસ', 'ಮತದಾನದ ದಿನ'],
  'Results & Counting': ['Results & Counting', 'परिणाम और गिनती', 'Results & Counting', 'ফলাফল ও গণনা', 'ఫలితాలు మరియు లెక్కింపు', 'निकाल आणि मोजणी', 'முடிவுகள் மற்றும் எண்ணிக்கை', 'પરિણામો અને ગણતરી', 'ಫಲಿತಾಂಶಗಳು ಮತ್ತು ಎಣಿಕೆ'],

  // Topics Descriptions
  'Learn the end-to-end flow of Indian elections.': ['Learn the end-to-end flow of Indian elections.', 'भारतीय चुनावों के शुरू से अंत तक के प्रवाह को जानें।', 'Learn the end-to-end flow of Indian elections.', 'ভারতীয় নির্বাচনের শুরু থেকে শেষ পর্যন্ত প্রবাহ জানুন।', 'భారతీయ ఎన్నికల ప్రారంభం నుండి ముగింపు వరకు ప్రవాహాన్ని తెలుసుకోండి.', 'भारतीय निवडणुकांचा सुरुवातीपासून शेवटपर्यंतचा प्रवाह जाणून घ्या.', 'இந்தியத் தேர்தல்களின் ஆரம்பம் முதல் முடிவு வரையிலான ஓட்டத்தைக் கற்றுக்கொள்ளுங்கள்.', 'ભારતીય ચૂંટણીઓનો શરૂઆતથી અંત સુધીનો પ્રવાહ જાણો.', 'ಭಾರತೀಯ ಚುನಾವಣೆಗಳ ಪ್ರಾರಂಭದಿಂದ ಅಂತ್ಯದವರೆಗಿನ ಹರಿವನ್ನು ತಿಳಿಯಿರಿ.'],
  'Step-by-step guide to get your Voter ID.': ['Step-by-step guide to get your Voter ID.', 'अपना वोटर आईडी प्राप्त करने के लिए चरण-दर-चरण मार्गदर्शिका।', 'Apna Voter ID paane ke liye step-by-step guide.', 'আপনার ভোটার আইডি পেতে ধাপে ধাপে গাইড।', 'మీ ఓటరు IDని పొందడానికి దశల వారీ మార్గదర్శి.', 'तुमचे मतदार ओळखपत्र मिळवण्यासाठी टप्प्याटप्प्याने मार्गदर्शक.', 'உங்கள் வாக்காளர் அடையாள அட்டையைப் பெறுவதற்கான படிப்படியான வழிகாட்டி.', 'તમારું મતદાર ID મેળવવા માટે પગલું-દર-પગલાં માર્ગદર્શિકા.', 'ನಿಮ್ಮ ಮತದಾರರ ID ಪಡೆಯಲು ಹಂತ-ಹಂತದ ಮಾರ್ಗದರ್ಶಿ.'],
  'Everything you need to know at the booth.': ['Everything you need to know at the booth.', 'बूथ पर आपको जो कुछ भी जानने की आवश्यकता है।', 'Booth par aapko jo kuch bhi janne ki zaroorat hai.', 'বুথে আপনার যা কিছু জানা দরকার।', 'బూత్ వద్ద మీరు తెలుసుకోవలసిన ప్రతిదీ.', 'बूथवर तुम्हाला जे काही माहित असणे आवश्यक आहे.', 'சாவடியில் நீங்கள் தெரிந்து கொள்ள வேண்டிய அனைத்தும்.', 'બૂથ પર તમારે જે જાણવાની જરૂર છે તે બધું.', 'ಬೂತ್‌ನಲ್ಲಿ ನೀವು ತಿಳಿದುಕೊಳ್ಳಬೇಕಾದ ಎಲ್ಲವೂ.'],
  'How your vote turns into a result.': ['How your vote turns into a result.', 'आपका वोट परिणाम में कैसे बदलता है।', 'Aapka vote result mein kaise badalta hai.', 'কিভাবে আপনার ভোট ফলাফলে পরিণত হয়।', 'మీ ఓటు ఫలితంగా ఎలా మారుతుంది.', 'तुमचे मत निकालात कसे बदलते.', 'உங்கள் வாக்கு எப்படி முடிவாக மாறுகிறது.', 'તમારો મત પરિણામમાં કેવી રીતે બદલાય છે.', 'ನಿಮ್ಮ ಮತವು ಫಲಿತಾಂಶವಾಗಿ ಹೇಗೆ ಬದಲಾಗುತ್ತದೆ.'],

  // Step Titles (Process)
  'Election Announcement': ['Election Announcement', 'चुनाव की घोषणा', 'Election Announcement', 'নির্বাচন ঘোষণা', 'ఎన్నికల ప్రకటన', 'निवडणूक घोषणा', 'தேர்தல் அறிவிப்பு', 'ચૂંટણી જાહેરાત', 'ಚುನಾವಣಾ ಪ್ರಕಟಣೆ'],
  'Nomination Phase': ['Nomination Phase', 'नामांकन चरण', 'Nomination Phase', 'মনোনয়ন পর্ব', 'నామినేషన్ దశ', 'नामांकन टप्पा', 'வேட்புமனு கட்டம்', 'નામાંકન તબક્કો', 'ನಾಮನಿರ್ದೇಶನ ಹಂತ'],
  'Campaigning': ['Campaigning', 'प्रचार', 'Campaigning', 'প্রচারণা', 'ప్రచారం', 'प्रचार', 'பிரச்சாரம்', 'પ્રચાર', 'ಪ್ರಚಾರ'],
  'Polling Day': ['Polling Day', 'मतदान का दिन', 'Polling Day', 'ভোটের দিন', 'పోలింగ్ రోజు', 'मतदानाचा दिवस', 'வாக்குப்பதிவு நாள்', 'મતદાનનો દિવસ', 'ಮತದಾನದ ದಿನ'],
  'EVM Sealing': ['EVM Sealing', 'EVM सीलिंग', 'EVM Sealing', 'ইভিএম সিলিং', 'EVM సీలింగ్', 'EVM सीलिंग', 'EVM சீலிங்', 'EVM સીલિંગ', 'EVM ಸೀಲಿಂಗ್'],
  'Counting & Declaration': ['Counting & Declaration', 'गिनती और घोषणा', 'Counting & Declaration', 'গণনা ও ঘোষণা', 'లెక్కింపు మరియు ప్రకటన', 'मोजणी आणि घोषणा', 'எண்ணிக்கை மற்றும் அறிவிப்பு', 'ગણતરી અને જાહેરાત', 'ಎಣಿಕೆ ಮತ್ತು ಪ್ರಕಟಣೆ'],

  // Step Descriptions (Process)
  'The ECI announces the schedule, implementing the Model Code of Conduct (MCC) immediately to ensure fair play.': ['The ECI announces the schedule, implementing the Model Code of Conduct (MCC) immediately to ensure fair play.', 'ECI निष्पक्ष खेल सुनिश्चित करने के लिए तुरंत आदर्श आचार संहिता (MCC) लागू करते हुए कार्यक्रम की घोषणा करता है।', 'The ECI announces the schedule, implementing the Model Code of Conduct (MCC) immediately to ensure fair play.', 'ECI একটি সুষ্ঠু খেলা নিশ্চিত করতে অবিলম্বে মডেল কোড অফ কন্ডাক্ট (MCC) প্রয়োগ করে তফসিল ঘোষণা করে।', 'ECI ఒక న్యాయమైన ఆటను నిర్ధారించడానికి మోడల్ కోడ్ ఆఫ్ కండక్ట్ (MCC)ను వెంటనే అమలు చేస్తూ షెడ్యూల్‌ను ప్రకటిస్తుంది.', 'ECI निष्पक्ष खेळ सुनिश्चित करण्यासाठी त्वरित आदर्श आचारसंहिता (MCC) लागू करत वेळापत्रक जाहीर करते.', 'ECI நியாயமான விளையாட்டை உறுதி செய்வதற்காக மாதிரி நடத்தை விதியை (MCC) உடனடியாகச் செயல்படுத்தி, அட்டவணையை அறிவிக்கிறது.', 'ECI વાજબી રમતની ખાતરી કરવા માટે મોડલ કોડ ઑફ કન્ડક્ટ (MCC) તાત્કાલિક લાગુ કરીને શેડ્યૂલની જાહેરાત કરે છે.', 'ECI ನ್ಯಾಯಯುತ ಆಟವನ್ನು ಖಚಿತಪಡಿಸಿಕೊಳ್ಳಲು ತಕ್ಷಣವೇ ಮಾದರಿ ನೀತಿ ಸಂಹಿತೆ (MCC) ಅನ್ನು ಜಾರಿಗೆ ತರುವ ಮೂಲಕ ವೇಳಾಪಟ್ಟಿಯನ್ನು ಪ್ರಕಟಿಸುತ್ತದೆ.'],
  'Candidates file nominations and security deposits. Officials then scrutinize papers to ensure eligibility.': ['Candidates file nominations and security deposits. Officials then scrutinize papers to ensure eligibility.', 'उम्मीदवार नामांकन और सुरक्षा जमा दाखिल करते हैं। फिर अधिकारी पात्रता सुनिश्चित करने के लिए कागजात की जांच करते हैं।', 'Candidates file nominations and security deposits. Officials then scrutinize papers to ensure eligibility.', 'প্রার্থীরা মনোনয়ন ও জামানত জমা দেন। এরপর কর্মকর্তারা যোগ্যতা নিশ্চিত করতে কাগজপত্র যাচাই করেন।', 'అభ్యర్థులు నామినేషన్లు మరియు భద్రతా డిపాజిట్లను దాఖలు చేస్తారు. అధికారులు ఆపై అర్హతను నిర్ధారించడానికి పత్రాలను పరిశీలిస్తారు.', 'उमेदवार नामांकन आणि सुरक्षा ठेव दाखल करतात. त्यानंतर अधिकारी पात्रता सुनिश्चित करण्यासाठी कागदपत्रांची छाननी करतात.', 'வேட்பாளர்கள் வேட்புமனு மற்றும் பாதுகாப்பு வைப்புத் தொகையை தாக்கல் செய்கிறார்கள். பின்னர் தகுதியை உறுதிப்படுத்த அதிகாரிகள் ஆவணங்களை ஆய்வு செய்கிறார்கள்.', 'ઉમેદવારો નામાંકન અને સુરક્ષા થાપણો ફાઇલ કરે છે. પછી અધિકારીઓ પાત્રતાની ખાતરી કરવા માટે કાગળોની ચકાસણી કરે છે.', 'ಅಭ್ಯರ್ಥಿಗಳು ನಾಮಪತ್ರ ಮತ್ತು ಭದ್ರತಾ ಠೇವಣಿಗಳನ್ನು ಸಲ್ಲಿಸುತ್ತಾರೆ. ನಂತರ ಅಧಿಕಾರಿಗಳು ಅರ್ಹತೆಯನ್ನು ಖಚಿತಪಡಿಸಿಕೊಳ್ಳಲು ಕಾಗದಗಳನ್ನು ಪರಿಶೀಲಿಸುತ್ತಾರೆ.'],
  'Parties release manifestos and hold rallies. Campaigning must stop 48 hours before the polling ends.': ['Parties release manifestos and hold rallies. Campaigning must stop 48 hours before the polling ends.', 'पार्टियां घोषणापत्र जारी करती हैं और रैलियां करती हैं। मतदान समाप्त होने से 48 घंटे पहले प्रचार बंद होना चाहिए।', 'Parties release manifestos and hold rallies. Campaigning must stop 48 hours before the polling ends.', 'দলগুলো ইশতেহার প্রকাশ করে এবং সমাবেশ করে। ভোটগ্রহণ শেষ হওয়ার ৪৮ ঘণ্টা আগে প্রচার বন্ধ করতে হবে।', 'పార్టీలు మేనిఫెస్టోలను విడుదల చేస్తాయి మరియు ర్యాలీలు నిర్వహిస్తాయి. పోలింగ్ ముగియడానికి 48 గంటల ముందు ప్రచారం నిలిపివేయాలి.', 'पक्ष जाहीरनामे प्रसिद्ध करतात आणि रॅली काढतात. मतदान संपण्याच्या 48 तास आधी प्रचार थांबला पाहिजे.', 'கட்சிகள் தேர்தல் அறிக்கைகளை வெளியிட்டு பேரணிகளை நடத்துகின்றன. வாக்குப்பதிவு முடிவதற்கு 48 மணி நேரத்திற்கு முன்னதாக பிரச்சாரம் நிறுத்தப்பட வேண்டும்.', 'પક્ષો મેનિફેસ્ટો બહાર પાડે છે અને રેલીઓ યોજે છે. મતદાન સમાપ્ત થવાના 48 કલાક પહેલા પ્રચાર બંધ થવો જોઈએ.', 'ಪಕ್ಷಗಳು ಪ್ರಣಾಳಿಕೆಗಳನ್ನು ಬಿಡುಗಡೆ ಮಾಡುತ್ತವೆ ಮತ್ತು ರ್‍ಯಾಲಿಗಳನ್ನು ನಡೆಸುತ್ತವೆ. ಮತದಾನ ಮುಗಿಯುವ 48 ಗಂಟೆಗಳ ಮೊದಲು ಪ್ರಚಾರವನ್ನು ನಿಲ್ಲಿಸಬೇಕು.'],
  'Voters across the constituency visit designated booths to cast their secret ballots using EVMs.': ['Voters across the constituency visit designated booths to cast their secret ballots using EVMs.', 'निर्वाचन क्षेत्र भर के मतदाता EVM का उपयोग करके अपना गुप्त मतदान करने के लिए नामित बूथों पर जाते हैं।', 'Voters across the constituency visit designated booths to cast their secret ballots using EVMs.', 'নির্বাচনী এলাকার ভোটাররা ইভিএম ব্যবহার করে তাদের গোপন ব্যালট দিতে নির্ধারিত বুথে যান।', 'నియోజకవర్గంలోని ఓటర్లు EVMలను ఉపయోగించి తమ రహస్య బ్యాలెట్లను వేయడానికి నియమించబడిన బూత్‌లను సందర్శిస్తారు.', 'मतदारसंघातील मतदार EVM चा वापर करून त्यांचे गुप्त मतदान करण्यासाठी नियुक्त बूथला भेट देतात.', 'தொகுதி முழுவதும் உள்ள வாக்காளர்கள் EVM களைப் பயன்படுத்தி தங்களின் ரகசிய வாக்குகளைச் செலுத்த நியமிக்கப்பட்ட சாவடிகளுக்குச் செல்கிறார்கள்.', 'મતવિસ્તારના મતદારો EVM નો ઉપયોગ કરીને તેમના ગુપ્ત મતદાન કરવા માટે નિયુક્ત બૂથની મુલાકાત લે છે.', 'ಕ್ಷೇತ್ರದಾದ್ಯಂತ ಇರುವ ಮತದಾರರು EVM ಗಳನ್ನು ಬಳಸಿ ತಮ್ಮ ರಹಸ್ಯ ಮತಗಳನ್ನು ಚಲಾಯಿಸಲು ಗೊತ್ತುಪಡಿಸಿದ ಬೂತ್‌ಗಳಿಗೆ ಭೇಟಿ ನೀಡುತ್ತಾರೆ.'],
  'After polling, EVMs and VVPATs are sealed in the presence of polling agents and moved to strongrooms.': ['After polling, EVMs and VVPATs are sealed in the presence of polling agents and moved to strongrooms.', 'मतदान के बाद, EVM और VVPAT को पोलिंग एजेंटों की उपस्थिति में सील कर दिया जाता है और स्ट्रांगरूम में ले जाया जाता है।', 'After polling, EVMs and VVPATs are sealed in the presence of polling agents and moved to strongrooms.', 'ভোটগ্রহণের পর, ইভিএম এবং ভিভিপিএটিগুলি পোলিং এজেন্টদের উপস্থিতিতে সিল করা হয় এবং স্ট্রংরুমে স্থানান্তরিত হয়।', 'పోలింగ్ తర్వాత, EVMలు మరియు VVPATలు పోలింగ్ ఏజెంట్ల సమక్షంలో సీల్ చేయబడి స్ట్రాంగ్‌రూమ్‌లకు తరలించబడతాయి.', 'मतदानानंतर, EVM आणि VVPAT हे पोलिंग एजंटच्या उपस्थितीत सील केले जातात आणि स्ट्राँगरूममध्ये हलवले जातात.', 'வாக்குப்பதிவுக்குப் பிறகு, EVM மற்றும் VVPAT ஆகியவை வாக்குப்பதிவு முகவர்களின் முன்னிலையில் சீல் வைக்கப்பட்டு ஸ்ட்ராங்ரூம்களுக்கு மாற்றப்படுகின்றன.', 'મતદાન પછી, EVM અને VVPAT ને પોલિંગ એજન્ટોની હાજરીમાં સીલ કરવામાં આવે છે અને સ્ટ્રોંગરૂમમાં ખસેડવામાં આવે છે.', 'ಮತದಾನದ ನಂತರ, EVM ಗಳು ಮತ್ತು VVPAT ಗಳನ್ನು ಪೋಲಿಂಗ್ ಏಜೆಂಟ್‌ಗಳ ಸಮ್ಮುಖದಲ್ಲಿ ಮೊಹರು ಮಾಡಲಾಗುತ್ತದೆ ಮತ್ತು ಸ್ಟ್ರಾಂಗ್‌ರೂಮ್‌ಗಳಿಗೆ ಸ್ಥಳಾಂತರಿಸಲಾಗುತ್ತದೆ.'],
  'Votes are counted on a scheduled day. The candidate with the highest votes is declared the winner.': ['Votes are counted on a scheduled day. The candidate with the highest votes is declared the winner.', 'निर्धारित दिन पर वोटों की गिनती की जाती है। सबसे अधिक वोट पाने वाले उम्मीदवार को विजेता घोषित किया जाता है।', 'Votes are counted on a scheduled day. The candidate with the highest votes is declared the winner.', 'নির্ধারিত দিনে ভোট গণনা করা হয়। সর্বোচ্চ ভোট পাওয়া প্রার্থীকে বিজয়ী ঘোষণা করা হয়।', 'షెడ్యూల్ చేయబడిన రోజున ఓట్లు లెక్కించబడతాయి. అత్యధిక ఓట్లు సాధించిన అభ్యర్థిని విజేతగా ప్రకటిస్తారు.', 'ठरलेल्या दिवशी मतांची मोजणी होते. सर्वाधिक मते मिळवणाऱ्या उमेदवाराला विजयी घोषित केले जाते.', 'திட்டமிடப்பட்ட நாளில் வாக்குகள் எண்ணப்படுகின்றன. அதிக வாக்குகள் பெற்ற வேட்பாளர் வெற்றி பெற்றவராக அறிவிக்கப்படுவார்.', 'નિર્ધારિત દિવસે મતોની ગણતરી કરવામાં આવે છે. સૌથી વધુ મતો ધરાવતા ઉમેદવારને વિજેતા જાહેર કરવામાં આવે છે.', 'ನಿಗದಿತ ದಿನದಂದು ಮತಗಳನ್ನು ಎಣಿಕೆ ಮಾಡಲಾಗುತ್ತದೆ. ಅತಿ ಹೆಚ್ಚು ಮತ ಪಡೆದ ಅಭ್ಯರ್ಥಿಯನ್ನು ವಿಜೇತ ಎಂದು ಘೋಷಿಸಲಾಗುತ್ತದೆ.'],

  // Step Titles (Registration)
  'Check Eligibility': ['Check Eligibility', 'पात्रता जांचें', 'Check Eligibility', 'যোগ্যতা পরীক্ষা করুন', 'అర్హతను తనిఖీ చేయండి', 'पात्रता तपासा', 'தகுதியைச் சரிபார்க்கவும்', 'પાત્રતા તપાસો', 'ಅರ್ಹತೆಯನ್ನು ಪರಿಶೀಲಿಸಿ'],
  'Online Form 6': ['Online Form 6', 'ऑनलाइन फॉर्म 6', 'Online Form 6', 'অনলাইন ফর্ম 6', 'ఆన్‌లైన్ ఫారమ్ 6', 'ऑनलाइन फॉर्म 6', 'ஆன்லைன் படிவம் 6', 'ઓનલાઈન ફોર્મ 6', 'ಆನ್‌ಲೈನ್ ಫಾರ್ಮ್ 6'],
  'Document Upload': ['Document Upload', 'दस्तावेज़ अपलोड', 'Document Upload', 'নথি আপলোড', 'పత్రం అప్‌లోడ్', 'दस्तऐवज अपलोड', 'ஆவணப் பதிவேற்றம்', 'દસ્તાવેજ અપલોડ', 'ಡಾಕ್ಯುಮೆಂಟ್ ಅಪ್‌ಲೋಡ್'],
  'Field Verification': ['Field Verification', 'क्षेत्र सत्यापन', 'Field Verification', 'মাঠ যাচাই', 'ఫీల్డ్ వెరిఫికేషన్', 'क्षेत्र सत्यापन', 'களச் சரிபார்ப்பு', 'ક્ષેત્ર ચકાસણી', 'ಕ್ಷೇತ್ರ ಪರಿಶೀಲನೆ'],
  'EPIC Generation': ['EPIC Generation', 'EPIC जनरेशन', 'EPIC Generation', 'ইপিআইসি জেনারেশন', 'EPIC జనరేషన్', 'EPIC जनरेशन', 'EPIC உருவாக்கம்', 'EPIC જનરેશન', 'EPIC ಉತ್ಪಾದನೆ'],
  'Card Delivery': ['Card Delivery', 'कार्ड डिलीवरी', 'Card Delivery', 'কার্ড বিতরণ', 'కార్డ్ డెలివరీ', 'कार्ड वितरण', 'கார்டு டெலிவரி', 'કાર્ડ ડિલિવરી', 'ಕಾರ್ಡ್ ವಿತರಣೆ'],

  // Step Descriptions (Registration)
  'You must be an Indian citizen, 18+ years old, and a resident of the polling area where you want to register.': ['You must be an Indian citizen, 18+ years old, and a resident of the polling area where you want to register.', 'आपको एक भारतीय नागरिक, 18+ वर्ष का और उस मतदान क्षेत्र का निवासी होना चाहिए जहां आप पंजीकरण करना चाहते हैं।', 'You must be an Indian citizen, 18+ years old, and a resident of the polling area where you want to register.', 'আপনাকে অবশ্যই একজন ভারতীয় নাগরিক, 18+ বছর বয়সী এবং যে ভোটকেন্দ্রে আপনি নিবন্ধন করতে চান তার বাসিন্দা হতে হবে।', 'మీరు భారతీయ పౌరులు, 18+ సంవత్సరాల వయస్సు మరియు మీరు నమోదు చేయాలనుకుంటున్న పోలింగ్ ప్రాంత నివాసి అయి ఉండాలి.', 'तुम्ही भारतीय नागरिक, 18+ वर्षांचे आणि ज्या मतदान क्षेत्रात तुम्हाला नोंदणी करायची आहे तेथील रहिवासी असणे आवश्यक आहे.', 'நீங்கள் ஒரு இந்தியக் குடிமகனாகவும், 18+ வயதுடையவராகவும், பதிவு செய்ய விரும்பும் வாக்குப்பதிவுப் பகுதியிலும் வசிப்பவராக இருக்க வேண்டும்.', 'તમારે ભારતીય નાગરિક, 18+ વર્ષના હોવા જોઈએ અને તે મતદાન ક્ષેત્રના નિવાસી હોવા જોઈએ જ્યાં તમે નોંધણી કરવા માંગો છો.', 'ನೀವು ಭಾರತೀಯ ಪ್ರಜೆಯಾಗಿರಬೇಕು, 18+ ವರ್ಷ ವಯಸ್ಸಿನವರಾಗಿರಬೇಕು ಮತ್ತು ನೀವು ನೋಂದಾಯಿಸಲು ಬಯಸುವ ಮತದಾನ ಪ್ರದೇಶದ ನಿವಾಸಿಯಾಗಿರಬೇಕು.'],
  'Visit the Voter Service Portal (voters.eci.gov.in) and fill Form 6 for new registration.': ['Visit the Voter Service Portal (voters.eci.gov.in) and fill Form 6 for new registration.', 'मतदाता सेवा पोर्टल (voters.eci.gov.in) पर जाएं और नए पंजीकरण के लिए फॉर्म 6 भरें।', 'Visit the Voter Service Portal (voters.eci.gov.in) and fill Form 6 for new registration.', 'ভোটার সার্ভিস পোর্টালে (voters.eci.gov.in) যান এবং নতুন নিবন্ধনের জন্য ফর্ম 6 পূরণ করুন।', 'కొత్త రిజిస్ట్రేషన్ కోసం ఓటరు సర్వీస్ పోర్టల్ (voters.eci.gov.in)ని సందర్శించండి మరియు ఫారమ్ 6ని పూరించండి.', 'नवीन नोंदणीसाठी मतदार सेवा पोर्टलला (voters.eci.gov.in) भेट द्या आणि फॉर्म 6 भरा.', 'புதிய பதிவுக்கு வாக்காளர் சேவை போர்ட்டலைப் (voters.eci.gov.in) பார்வையிட்டு படிவம் 6ஐப் பூர்த்தி செய்யவும்.', 'નવા નોંધણી માટે મતદાર સેવા પોર્ટલ (voters.eci.gov.in) ની મુલાકાત લો અને ફોર્મ 6 ભરો.', 'ಹೊಸ ನೋಂದಣಿಗಾಗಿ ಮತದಾರ ಸೇವಾ ಪೋರ್ಟಲ್‌ಗೆ (voters.eci.gov.in) ಭೇಟಿ ನೀಡಿ ಮತ್ತು ಫಾರ್ಮ್ 6 ಅನ್ನು ಭರ್ತಿ ಮಾಡಿ.'],
  'Upload a recent passport photo, age proof (Aadhaar/10th Cert), and address proof (Utility bill/Passport).': ['Upload a recent passport photo, age proof (Aadhaar/10th Cert), and address proof (Utility bill/Passport).', 'एक हालिया पासपोर्ट फोटो, आयु प्रमाण (आधार/10वीं प्रमाणपत्र), और पता प्रमाण (उपयोगिता बिल/पासपोर्ट) अपलोड करें।', 'Upload a recent passport photo, age proof (Aadhaar/10th Cert), and address proof (Utility bill/Passport).', 'সাম্প্রতিক একটি পাসপোর্ট ছবি, বয়সের প্রমাণ (আধার/দশম সার্টিফিকেট), এবং ঠিকানার প্রমাণ (ইউটিলিটি বিল/পাসপোর্ট) আপলোড করুন।', 'ఇటీవలి పాస్‌పోర్ట్ ఫోటో, వయస్సు రుజువు (ఆధార్/10వ సర్టిఫికేట్) మరియు చిరునామా రుజువు (యుటిలిటీ బిల్లు/పాస్‌పోర్ట్) అప్‌లోడ్ చేయండి.', 'अलीकडील पासपोर्ट फोटो, वयाचा पुरावा (आधार/10वी प्रमाणपत्र) आणि पत्त्याचा पुरावा (युटिलिटी बिल/पासपोर्ट) अपलोड करा.', 'சமீபத்திய பாஸ்போர்ட் புகைப்படம், வயதுச் சான்று (ஆதார்/10வது சான்றிதழ்) மற்றும் முகவரிச் சான்று (பயன்பாட்டு மசோதா/பாஸ்போர்ட்) ஆகியவற்றைப் பதிவேற்றவும்.', 'તાજેતરનો પાસપોર્ટ ફોટો, ઉંમરનો પુરાવો (આધાર/10મું પ્રમાણપત્ર) અને સરનામાનો પુરાવો (ઉપયોગિતા બિલ/પાસપોર્ટ) અપલોડ કરો.', 'ಇತ್ತೀಚಿನ ಪಾಸ್‌ಪೋರ್ಟ್ ಫೋಟೋ, ವಯಸ್ಸಿನ ಪುರಾವೆ (ಆಧಾರ್/10ನೇ ಪ್ರಮಾಣಪತ್ರ) ಮತ್ತು ವಿಳಾಸದ ಪುರಾವೆ (ಯುಟಿಲಿಟಿ ಬಿಲ್/ಪಾಸ್‌ಪೋರ್ಟ್) ಅಪ್‌ಲೋಡ್ ಮಾಡಿ.'],
  'A Booth Level Officer (BLO) may visit your home to verify the details provided in your application.': ['A Booth Level Officer (BLO) may visit your home to verify the details provided in your application.', 'आपके आवेदन में दिए गए विवरणों को सत्यापित करने के लिए एक बूथ स्तर अधिकारी (BLO) आपके घर आ सकता है।', 'A Booth Level Officer (BLO) may visit your home to verify the details provided in your application.', 'আপনার আবেদনে দেওয়া বিশদ যাচাই করতে একজন বুথ লেভেল অফিসার (BLO) আপনার বাড়িতে যেতে পারেন।', 'మీ అప్లికేషన్‌లో అందించిన వివరాలను ధృవీకరించడానికి బూత్ లెవల్ ఆఫీసర్ (BLO) మీ ఇంటిని సందర్శించవచ్చు.', 'तुमच्या अर्जामध्ये दिलेले तपशील सत्यापित करण्यासाठी एक बूथ लेव्हल ऑफिसर (BLO) तुमच्या घरी भेट देऊ शकतो.', 'உங்கள் விண்ணப்பத்தில் கொடுக்கப்பட்டுள்ள விவரங்களைச் சரிபார்க்க, பூத் நிலை அதிகாரி (BLO) உங்கள் வீட்டிற்கு வரலாம்.', 'તમારી અરજીમાં આપેલી વિગતોની ચકાસણી કરવા માટે બૂથ લેવલ ઓફિસર (BLO) તમારા ઘરે મુલાકાત લઈ શકે છે.', 'ನಿಮ್ಮ ಅಪ್ಲಿಕೇಶನ್‌ನಲ್ಲಿ ಒದಗಿಸಲಾದ ವಿವರಗಳನ್ನು ಪರಿಶೀಲಿಸಲು ಬೂತ್ ಮಟ್ಟದ ಅಧಿಕಾರಿ (BLO) ನಿಮ್ಮ ಮನೆಗೆ ಭೇಟಿ ನೀಡಬಹುದು.'],
  'Once approved, your Electoral Photo Identity Card (EPIC) is generated and a unique Voter ID number is assigned.': ['Once approved, your Electoral Photo Identity Card (EPIC) is generated and a unique Voter ID number is assigned.', 'एक बार स्वीकृत होने के बाद, आपका चुनावी फोटो पहचान पत्र (EPIC) उत्पन्न होता है और एक अद्वितीय वोटर आईडी नंबर आवंटित किया जाता है।', 'Once approved, your Electoral Photo Identity Card (EPIC) is generated and a unique Voter ID number is assigned.', 'একবার অনুমোদিত হলে, আপনার ইলেকটোরাল ফটো আইডেন্টিটি কার্ড (EPIC) তৈরি হয় এবং একটি অনন্য ভোটার আইডি নম্বর বরাদ্দ করা হয়।', 'ఆమోదించబడిన తర్వాత, మీ ఎలక్టోరల్ ఫోటో ఐడెంటిటీ కార్డ్ (EPIC) రూపొందించబడుతుంది మరియు ప్రత్యేక ఓటరు ID నంబర్ కేటాయించబడుతుంది.', 'एकदा मंजूर झाल्यानंतर, तुमचे इलेक्टोरल फोटो आयडेंटिटी कार्ड (EPIC) जनरेट केले जाते आणि एक अद्वितीय मतदार ओळखपत्र क्रमांक नियुक्त केला जातो.', 'ஒப்புதல் அளிக்கப்பட்டதும், உங்கள் தேர்தல் புகைப்பட அடையாள அட்டை (EPIC) உருவாக்கப்பட்டு தனிப்பட்ட வாக்காளர் அடையாள எண் ஒதுக்கப்படும்.', 'એકવાર મંજૂર થયા પછી, તમારું ઇલેક્ટોરલ ફોટો આઇડેન્ટિટી કાર્ડ (EPIC) જનરેટ થાય છે અને એક અનન્ય મતદાર ID નંબર સોંપવામાં આવે છે.', 'ಅನುಮೋದಿಸಿದ ನಂತರ, ನಿಮ್ಮ ಚುನಾವಣಾ ಭಾವಚಿತ್ರ ಗುರುತಿನ ಚೀಟಿ (EPIC) ಅನ್ನು ರಚಿಸಲಾಗುತ್ತದೆ ಮತ್ತು ವಿಶಿಷ್ಟ ಮತದಾರ ID ಸಂಖ್ಯೆಯನ್ನು ನಿಯೋಜಿಸಲಾಗುತ್ತದೆ.'],
  'Your physical Voter ID card is sent to your registered address via Speed Post free of cost.': ['Your physical Voter ID card is sent to your registered address via Speed Post free of cost.', 'आपका भौतिक वोटर आईडी कार्ड बिना किसी लागत के स्पीड पोस्ट के माध्यम से आपके पंजीकृत पते पर भेजा जाता है।', 'Your physical Voter ID card is sent to your registered address via Speed Post free of cost.', 'আপনার ফিজিক্যাল ভোটার আইডি কার্ড বিনামূল্যে স্পিড পোস্টের মাধ্যমে আপনার নিবন্ধিত ঠিকানায় পাঠানো হয়।', 'మీ భౌతిక ఓటరు ID కార్డ్ ఉచితంగా స్పీడ్ పోస్ట్ ద్వారా మీ నమోదిత చిరునామాకు పంపబడుతుంది.', 'तुमचे भौतिक मतदार ओळखपत्र विनामूल्य स्पीड पोस्टद्वारे तुमच्या नोंदणीकृत पत्त्यावर पाठवले जाते.', 'உங்கள் பிசிகல் வாக்காளர் அடையாள அட்டை ஸ்பீட் போஸ்ட் மூலம் உங்கள் பதிவு செய்யப்பட்ட முகவரிக்கு இலவசமாக அனுப்பப்படும்.', 'તમારું ભૌતિક મતદાર ID કાર્ડ તમારા નોંધાયેલ સરનામાં પર સ્પીડ પોસ્ટ દ્વારા વિનામૂલ્યે મોકલવામાં આવે છે.', 'ನಿಮ್ಮ ಭೌತಿಕ ಮತದಾರರ ID ಕಾರ್ಡ್ ಅನ್ನು ಸ್ಪೀಡ್ ಪೋಸ್ಟ್ ಮೂಲಕ ನಿಮ್ಮ ನೋಂದಾಯಿತ ವಿಳಾಸಕ್ಕೆ ಉಚಿತವಾಗಿ ಕಳುಹಿಸಲಾಗುತ್ತದೆ.'],

  // Step Titles (Voting Day)
  'Find Your Booth': ['Find Your Booth', 'अपना बूथ खोजें', 'Find Your Booth', 'আপনার বুথ খুঁজুন', 'మీ బూత్‌ను కనుగొనండి', 'तुमचे बूथ शोधा', 'உங்கள் சாவடியைக் கண்டுபிடி', 'તમારું બૂથ શોધો', 'ನಿಮ್ಮ ಬೂತ್ ಹುಡುಕಿ'],
  'Entry & Queue': ['Entry & Queue', 'प्रवेश और कतार', 'Entry & Queue', 'প্রবেশ এবং সারি', 'ప్రవేశం మరియు క్యూ', 'प्रवेश आणि रांग', 'நுழைவு மற்றும் வரிசை', 'પ્રવેશ અને કતાર', 'ಪ್ರವೇಶ ಮತ್ತು ಸರತಿ'],
  'First Polling Officer': ['First Polling Officer', 'प्रथम मतदान अधिकारी', 'First Polling Officer', 'প্রথম পোলিং অফিসার', 'మొదటి పోలింగ్ అధికారి', 'प्रथम मतदान अधिकारी', 'முதல் வாக்குச்சாவடி அதிகாரி', 'પ્રથમ મતદાન અધિકારી', 'ಮೊದಲ ಮತಗಟ್ಟೆ ಅಧಿಕಾರಿ'],
  'Inking & Slip': ['Inking & Slip', 'स्याही और पर्ची', 'Inking & Slip', 'কালি এবং স্লিপ', 'ఇంకింగ్ మరియు స్లిప్', 'शाई आणि स्लिप', 'இங்க் மற்றும் ஸ்லிப்', 'શાહી અને સ્લિપ', 'ಇಂಕಿಂಗ್ ಮತ್ತು ಸ್ಲಿಪ್'],
  'Casting the Vote': ['Casting the Vote', 'वोट डालना', 'Casting the Vote', 'ভোট দান', 'ఓటు వేయడం', 'मतदान', 'வாக்களிப்பது', 'મતદાન', 'ಮತದಾನ'],
  'VVPAT Verification': ['VVPAT Verification', 'VVPAT सत्यापन', 'VVPAT Verification', 'ভিভিপিএটি যাচাইকরণ', 'VVPAT ధృవీకరణ', 'VVPAT सत्यापन', 'VVPAT சரிபார்ப்பு', 'VVPAT ચકાસણી', 'VVPAT ಪರಿಶೀಲನೆ'],

  // Step Descriptions (Voting Day)
  'Check your name in the voter list online to find your specific Polling Station and Part Number.': ['Check your name in the voter list online to find your specific Polling Station and Part Number.', 'अपना विशिष्ट मतदान केंद्र और भाग संख्या खोजने के लिए ऑनलाइन मतदाता सूची में अपना नाम जांचें।', 'Check your name in the voter list online to find your specific Polling Station and Part Number.', 'আপনার নির্দিষ্ট পোলিং স্টেশন এবং পার্ট নম্বর খুঁজতে অনলাইনে ভোটার তালিকায় আপনার নাম পরীক্ষা করুন।', 'మీ నిర్దిష్ట పోలింగ్ స్టేషన్ మరియు పార్ట్ నంబర్‌ను కనుగొనడానికి ఆన్‌లైన్‌లో ఓటరు జాబితాలో మీ పేరును తనిఖీ చేయండి.', 'तुमचे विशिष्ट मतदान केंद्र आणि भाग क्रमांक शोधण्यासाठी ऑनलाइन मतदार यादीत तुमचे नाव तपासा.', 'உங்கள் குறிப்பிட்ட வாக்குச்சாவடி மற்றும் பகுதி எண்ணைக் கண்டறிய ஆன்லைனில் வாக்காளர் பட்டியலில் உங்கள் பெயரைச் சரிபார்க்கவும்.', 'તમારું ચોક્કસ મતદાન મથક અને ભાગ નંબર શોધવા માટે ઓનલાઈન મતદાર યાદીમાં તમારું નામ તપાસો.', 'ನಿಮ್ಮ ನಿರ್ದಿಷ್ಟ ಮತಗಟ್ಟೆ ಮತ್ತು ಭಾಗ ಸಂಖ್ಯೆಯನ್ನು ಹುಡುಕಲು ಆನ್‌ಲೈನ್‌ನಲ್ಲಿ ಮತದಾರರ ಪಟ್ಟಿಯಲ್ಲಿ ನಿಮ್ಮ ಹೆಸರನ್ನು ಪರಿಶೀಲಿಸಿ.'],
  'Reach the booth with your EPIC or any of the 12 alternative valid photo ID proofs.': ['Reach the booth with your EPIC or any of the 12 alternative valid photo ID proofs.', 'अपने EPIC या 12 वैकल्पिक वैध फोटो पहचान प्रमाणों में से किसी के साथ बूथ पर पहुंचें।', 'Reach the booth with your EPIC or any of the 12 alternative valid photo ID proofs.', 'আপনার ইপিক (EPIC) বা ১২টি বিকল্প বৈধ ফটো আইডি প্রমাণের যেকোনো একটি নিয়ে বুথে পৌঁছান।', 'మీ EPIC లేదా 12 ప్రత్యామ్నాయ చెల్లుబాటు అయ్యే ఫోటో ID ప్రూఫ్‌లలో దేనితోనైనా బూత్‌కు చేరుకోండి.', 'तुमचे EPIC किंवा 12 पर्यायी वैध फोटो ओळख पुराव्यांपैकी कोणत्याहीसह बूथवर पोहोचा.', 'உங்கள் EPIC அல்லது 12 மாற்று செல்லுபடியாகும் புகைப்பட அடையாளச் சான்றுகளில் ஏதேனும் ஒன்றைக் கொண்டு சாவடியை அடையுங்கள்.', 'તમારા EPIC અથવા 12 વૈકલ્પિક માન્ય ફોટો ID પુરાવાઓમાંથી કોઈપણ સાથે બૂથ પર પહોંચો.', 'ನಿಮ್ಮ EPIC ಅಥವಾ 12 ಪರ್ಯಾಯ ಮಾನ್ಯವಾದ ಫೋಟೋ ID ಪುರಾವೆಗಳಲ್ಲಿ ಯಾವುದಾದರೂ ಒಂದರೊಂದಿಗೆ ಬೂತ್‌ಗೆ ತಲುಪಿ.'],
  'The officer checks your name in the electoral roll and verifies your identity document.': ['The officer checks your name in the electoral roll and verifies your identity document.', 'अधिकारी मतदाता सूची में आपके नाम की जांच करता है और आपके पहचान दस्तावेज का सत्यापन करता है।', 'The officer checks your name in the electoral roll and verifies your identity document.', 'কর্মকর্তা ভোটার তালিকায় আপনার নাম পরীক্ষা করেন এবং আপনার পরিচয় নথি যাচাই করেন।', 'అధికారి ఎలక్టోరల్ రోల్‌లో మీ పేరును తనిఖీ చేస్తారు మరియు మీ గుర్తింపు పత్రాన్ని ధృవీకరిస్తారు.', 'अधिकारी मतदार यादीत तुमचे नाव तपासतात आणि तुमच्या ओळखपत्राची पडताळणी करतात.', 'அதிகாரி வாக்காளர் பட்டியலில் உங்கள் பெயரைச் சரிபார்த்து, உங்கள் அடையாள ஆவணத்தைச் சரிபார்க்கிறார்.', 'અધિકારી મતદાર યાદીમાં તમારું નામ તપાસે છે અને તમારા ઓળખ દસ્તાવેજની ચકાસણી કરે છે.', 'ಅಧಿಕಾರಿಯು ಮತದಾರರ ಪಟ್ಟಿಯಲ್ಲಿ ನಿಮ್ಮ ಹೆಸರನ್ನು ಪರಿಶೀಲಿಸುತ್ತಾರೆ ಮತ್ತು ನಿಮ್ಮ ಗುರುತಿನ ದಾಖಲೆಯನ್ನು ಪರಿಶೀಲಿಸುತ್ತಾರೆ.'],
  'The second officer marks your finger with indelible ink, records your signature, and gives you a signed slip.': ['The second officer marks your finger with indelible ink, records your signature, and gives you a signed slip.', 'दूसरा अधिकारी अमिट स्याही से आपकी उंगली पर निशान लगाता है, आपके हस्ताक्षर रिकॉर्ड करता है, और आपको एक हस्ताक्षरित पर्ची देता है।', 'The second officer marks your finger with indelible ink, records your signature, and gives you a signed slip.', 'দ্বিতীয় কর্মকর্তা অমোচনীয় কালি দিয়ে আপনার আঙুলে দাগ দেন, আপনার স্বাক্ষর রেকর্ড করেন এবং আপনাকে একটি স্বাক্ষরিত স্লিপ দেন।', 'రెండవ అధికారి మీ వేలికి చెరగని సిరాతో గుర్తు పెట్టారు, మీ సంతకాన్ని నమోదు చేస్తారు మరియు మీకు సంతకం చేసిన స్లిప్‌ను అందజేస్తారు.', 'दुसरा अधिकारी तुमच्या बोटावर न पुसणाऱ्या शाईने खूण करतो, तुमची स्वाक्षरी नोंदवतो आणि तुम्हाला एक स्वाक्षरी केलेली स्लिप देतो.', 'இரண்டாவது அதிகாரி அழிக்க முடியாத மையால் உங்கள் விரலைக் குறிக்கிறார், உங்கள் கையொப்பத்தைப் பதிவுசெய்து, கையொப்பமிடப்பட்ட சீட்டை உங்களுக்கு வழங்குகிறார்.', 'બીજો અધિકારી તમારી આંગળી પર અદમ્ય શાહીથી નિશાન બનાવે છે, તમારી સહી નોંધે છે અને તમને સહી કરેલી સ્લિપ આપે છે.', 'ಎರಡನೇ ಅಧಿಕಾರಿಯು ಅಳಿಸಲಾಗದ ಶಾಯಿಯಿಂದ ನಿಮ್ಮ ಬೆರಳನ್ನು ಗುರುತಿಸುತ್ತಾರೆ, ನಿಮ್ಮ ಸಹಿಯನ್ನು ದಾಖಲಿಸುತ್ತಾರೆ ಮತ್ತು ಸಹಿ ಮಾಡಿದ ಸ್ಲಿಪ್ ಅನ್ನು ನಿಮಗೆ ನೀಡುತ್ತಾರೆ.'],
  'Go to the voting compartment, press the blue button next to your candidate on the EVM.': ['Go to the voting compartment, press the blue button next to your candidate on the EVM.', 'मतदान कक्ष में जाएं, EVM पर अपने उम्मीदवार के बगल में नीला बटन दबाएं।', 'Go to the voting compartment, press the blue button next to your candidate on the EVM.', 'ভোটের বগিতে যান, ইভিএম-এ আপনার প্রার্থীর পাশের নীল বোতাম টিপুন।', 'ఓటింగ్ కంపార్ట్‌మెంట్‌కు వెళ్లి, EVMలో మీ అభ్యర్థి పక్కన ఉన్న నీలిరంగు బటన్‌ను నొక్కండి.', 'मतदान कक्षात जा, EVM वर तुमच्या उमेदवारापुढील निळे बटण दाबा.', 'வாக்குப்பதிவு அறைக்குச் சென்று, EVM இல் உங்கள் வேட்பாளருக்கு அடுத்துள்ள நீல நிற பட்டனை அழுத்தவும்.', 'મતદાન કમ્પાર્ટમેન્ટમાં જાઓ, EVM પર તમારા ઉમેદવારની બાજુમાં આવેલ વાદળી બટન દબાવો.', 'ಮತದಾನದ ವಿಭಾಗಕ್ಕೆ ಹೋಗಿ, EVM ನಲ್ಲಿ ನಿಮ್ಮ ಅಭ್ಯರ್ಥಿಯ ಮುಂದಿನ ನೀಲಿ ಗುಂಡಿಯನ್ನು ಒತ್ತಿರಿ.'],
  'Check the VVPAT glass. A slip showing your candidate will be visible for 7 seconds before dropping.': ['Check the VVPAT glass. A slip showing your candidate will be visible for 7 seconds before dropping.', 'VVPAT ग्लास की जाँच करें। आपके उम्मीदवार को दिखाने वाली एक पर्ची गिरने से पहले 7 सेकंड तक दिखाई देगी।', 'Check the VVPAT glass. A slip showing your candidate will be visible for 7 seconds before dropping.', 'ভিভিপিএটি গ্লাস পরীক্ষা করুন। আপনার প্রার্থীকে দেখানো একটি স্লিপ নামার আগে ৭ সেকেন্ডের জন্য দেখা যাবে।', 'VVPAT గ్లాస్‌ని తనిఖీ చేయండి. మీ అభ్యర్థిని చూపే స్లిప్ డ్రాప్ అయ్యే ముందు 7 సెకన్ల పాటు కనిపిస్తుంది.', 'VVPAT ग्लास तपासा. तुमचा उमेदवार दर्शवणारी स्लिप खाली पडण्यापूर्वी 7 सेकंद दिसेल.', 'VVPAT கண்ணாடியைச் சரிபார்க்கவும். உங்கள் வேட்பாளரைக் காட்டும் சீட்டு கீழே விழுவதற்கு முன் 7 வினாடிகள் தெரியும்.', 'VVPAT ગ્લાસ તપાસો. તમારા ઉમેદવારને દર્શાવતી સ્લિપ પડતા પહેલા 7 સેકન્ડ માટે દેખાશે.', 'VVPAT ಗ್ಲಾಸ್ ಅನ್ನು ಪರಿಶೀಲಿಸಿ. ನಿಮ್ಮ ಅಭ್ಯರ್ಥಿಯನ್ನು ತೋರಿಸುವ ಸ್ಲಿಪ್ ಬೀಳುವ ಮೊದಲು 7 ಸೆಕೆಂಡುಗಳ ಕಾಲ ಗೋಚರಿಸುತ್ತದೆ.'],

  // Step Titles (Results)
  'Strongroom Security': ['Strongroom Security', 'स्ट्रांगरूम सुरक्षा', 'Strongroom Security', 'স্ট্রংরুম নিরাপত্তা', 'స్ట్రాంగ్‌రూమ్ భద్రత', 'स्ट्राँगरूम सुरक्षा', 'ஸ்ட்ராங்ரூம் பாதுகாப்பு', 'સ્ટ્રોંગરૂમ સુરક્ષા', 'ಸ್ಟ್ರಾಂಗ್‌ರೂಮ್ ಭದ್ರತೆ'],
  'Counting Center Setup': ['Counting Center Setup', 'मतगणना केंद्र की स्थापना', 'Counting Center Setup', 'গণনা কেন্দ্র সেটআপ', 'కౌంటింగ్ సెంటర్ సెటప్', 'मतमोजणी केंद्र सेटअप', 'எண்ணும் மைய அமைப்பு', 'ગણતરી કેન્દ્ર સેટઅપ', 'ಎಣಿಕೆ ಕೇಂದ್ರ ಸೆಟಪ್'],
  'Round-wise Counting': ['Round-wise Counting', 'राउंड-वार गिनती', 'Round-wise Counting', 'রাউন্ড-ওয়াইজ গণনা', 'రౌండ్ వారీగా కౌంటింగ్', 'फेरीनिहाय मोजणी', 'சுற்று வாரியாக எண்ணுதல்', 'રાઉન્ડ મુજબ ગણતરી', 'ಸುತ್ತಿನ-ವಾರು ಎಣಿಕೆ'],
  'VVPAT Slip Audit': ['VVPAT Slip Audit', 'VVPAT पर्ची ऑडिट', 'VVPAT Slip Audit', 'ভিভিপিএটি স্লিপ অডিট', 'VVPAT స్లిప్ ఆడిట్', 'VVPAT स्लिप ऑडिट', 'VVPAT ஸ்லிப் தணிக்கை', 'VVPAT સ્લિપ ઓડિટ', 'VVPAT ಸ್ಲಿಪ್ ಆಡಿಟ್'],
  'Final Tabulation': ['Final Tabulation', 'अंतिम सारणीकरण', 'Final Tabulation', 'চূড়ান্ত সারণি', 'చివరి పట్టిక', 'अंतिम सारणीकरण', 'இறுதி அட்டவணை', 'અંતિમ કોષ્ટક', 'ಅಂತಿಮ ಪಟ್ಟಿ'],
  'Certificate of Election': ['Certificate of Election', 'चुनाव का प्रमाण पत्र', 'Certificate of Election', 'নির্বাচনের শংসাপত্র', 'ఎన్నికల ధృవీకరణ పత్రం', 'निवडणुकीचे प्रमाणपत्र', 'தேர்தல் சான்றிதழ்', 'ચૂંટણીનું પ્રમાણપત્ર', 'ಚುನಾವಣಾ ಪ್ರಮಾಣಪತ್ರ'],

  // Step Descriptions (Results)
  'EVMs are kept in double-locked strongrooms with 24/7 CCTV and multi-tier armed security until counting day.': ['EVMs are kept in double-locked strongrooms with 24/7 CCTV and multi-tier armed security until counting day.', 'EVM को मतगणना के दिन तक 24/7 CCTV और मल्टी-टियर सशस्त्र सुरक्षा के साथ डबल-लॉक स्ट्रांगरूम में रखा जाता है।', 'EVMs are kept in double-locked strongrooms with 24/7 CCTV and multi-tier armed security until counting day.', 'ভোট গণনার দিন পর্যন্ত ইভিএমগুলি ২৪/৭ সিসিটিভি এবং বহু-স্তরীয় সশস্ত্র নিরাপত্তা সহ ডাবল-লক করা স্ট্রংরুমে রাখা হয়।', 'కౌంటింగ్ రోజు వరకు EVMలు 24/7 CCTV మరియు బహుళ-స్థాయి సాయుధ భద్రతతో డబుల్-లాక్ చేయబడిన స్ట్రాంగ్‌రూమ్‌లలో ఉంచబడతాయి.', 'मतमोजणीच्या दिवसापर्यंत EVM 24/7 CCTV आणि बहुस्तरीय सशस्त्र सुरक्षिततेसह दुहेरी-कुलूपबंद स्ट्राँगरूममध्ये ठेवल्या जातात.', 'வாக்கு எண்ணும் நாள் வரை 24/7 சிசிடிவி மற்றும் பல அடுக்கு ஆயுத பாதுகாப்புடன் கூடிய இரட்டை பூட்டப்பட்ட ஸ்ட்ராங்ரூம்களில் ஈவிஎம்கள் வைக்கப்பட்டுள்ளன.', 'મતગણતરીના દિવસ સુધી 24/7 CCTV અને બહુ-સ્તરીય સશસ્ત્ર સુરક્ષા સાથે EVM ને ડબલ-લોક સ્ટ્રોંગરૂમમાં રાખવામાં આવે છે.', 'ಎಣಿಕೆಯ ದಿನದವರೆಗೆ 24/7 CCTV ಮತ್ತು ಬಹು-ಹಂತದ ಸಶಸ್ತ್ರ ಭದ್ರತೆಯೊಂದಿಗೆ ಡಬಲ್-ಲಾಕ್ ಮಾಡಲಾದ ಸ್ಟ್ರಾಂಗ್‌ರೂಮ್‌ಗಳಲ್ಲಿ EVM ಗಳನ್ನು ಇರಿಸಲಾಗುತ್ತದೆ.'],
  'Counting happens at designated centers under strict supervision of the Returning Officer (RO).': ['Counting happens at designated centers under strict supervision of the Returning Officer (RO).', 'रिटर्निंग ऑफिसर (RO) की कड़ी निगरानी में नामित केंद्रों पर मतगणना होती है।', 'Counting happens at designated centers under strict supervision of the Returning Officer (RO).', 'রিটার্নিং অফিসারের (RO) কঠোর তত্ত্বাবধানে নির্ধারিত কেন্দ্রে গণনা হয়।', 'రిటర్నింగ్ ఆఫీసర్ (RO) యొక్క కఠినమైన పర్యవేక్షణలో నియమించబడిన కేంద్రాలలో కౌంటింగ్ జరుగుతుంది.', 'रिटर्निंग ऑफिसर (RO) च्या कडक देखरेखीखाली नियुक्त केंद्रांवर मतमोजणी होते.', 'ரிட்டர்னிங் அதிகாரியின் (RO) கடுமையான மேற்பார்வையின் கீழ் நியமிக்கப்பட்ட மையங்களில் எண்ணிக்கை நடைபெறுகிறது.', 'રીટર્નીંગ ઓફિસર (RO) ની કડક દેખરેખ હેઠળ નિયુક્ત કેન્દ્રો પર ગણતરી થાય છે.', 'ರಿಟರ್ನಿಂಗ್ ಆಫೀಸರ್ (RO) ಅವರ ಕಟ್ಟುನಿಟ್ಟಾದ ಮೇಲ್ವಿಚಾರಣೆಯಲ್ಲಿ ಗೊತ್ತುಪಡಿಸಿದ ಕೇಂದ್ರಗಳಲ್ಲಿ ಎಣಿಕೆ ನಡೆಯುತ್ತದೆ.'],
  'EVMs are opened round-by-round. Results for each machine are recorded in Form 17C.': ['EVMs are opened round-by-round. Results for each machine are recorded in Form 17C.', 'EVM को राउंड-बाय-राउंड खोला जाता है। प्रत्येक मशीन के परिणाम फॉर्म 17C में दर्ज किए जाते हैं।', 'EVMs are opened round-by-round. Results for each machine are recorded in Form 17C.', 'ইভিএমগুলি রাউন্ড-বাই-রাউন্ড খোলা হয়। প্রতিটি মেশিনের ফলাফল 17C ফর্মে রেকর্ড করা হয়।', 'EVMలు రౌండ్లవారీగా తెరవబడతాయి. ప్రతి యంత్రం యొక్క ఫలితాలు ఫారమ్ 17Cలో నమోదు చేయబడతాయి.', 'ईव्हीएम फेरी-बाय-फेरी उघडले जातात. प्रत्येक मशीनचा निकाल फॉर्म 17C मध्ये नोंदवला जातो.', 'ஈவிஎம்கள் சுற்று வாரியாக திறக்கப்படும். ஒவ்வொரு இயந்திரத்தின் முடிவுகளும் படிவம் 17C இல் பதிவு செய்யப்பட்டுள்ளன.', 'ઇવીએમ રાઉન્ડ-બાય-રાઉન્ડ ખોલવામાં આવે છે. દરેક મશીન માટેના પરિણામો ફોર્મ 17C માં નોંધવામાં આવે છે.', 'ಇವಿಎಂಗಳನ್ನು ರೌಂಡ್-ಬೈ-ರೌಂಡ್ ತೆರೆಯಲಾಗುತ್ತದೆ. ಪ್ರತಿಯೊಂದು ಯಂತ್ರದ ಫಲಿತಾಂಶಗಳನ್ನು ಫಾರ್ಮ್ 17C ನಲ್ಲಿ ದಾಖಲಿಸಲಾಗುತ್ತದೆ.'],
  'Mandatory physical counting of VVPAT slips from 5 randomly selected polling stations per constituency.': ['Mandatory physical counting of VVPAT slips from 5 randomly selected polling stations per constituency.', 'प्रति निर्वाचन क्षेत्र 5 यादृच्छिक रूप से चयनित मतदान केंद्रों से VVPAT पर्चियों की अनिवार्य भौतिक गिनती।', 'Mandatory physical counting of VVPAT slips from 5 randomly selected polling stations per constituency.', 'প্রতি নির্বাচনী এলাকার ৫টি এলোমেলোভাবে নির্বাচিত পোলিং স্টেশন থেকে ভিভিপিএটি স্লিপগুলির বাধ্যতামূলক শারীরিক গণনা।', 'ప్రతి నియోజకవర్గానికి యాదృచ్ఛికంగా ఎంపిక చేయబడిన 5 పోలింగ్ స్టేషన్ల నుండి VVPAT స్లిప్‌ల యొక్క తప్పనిసరి భౌతిక లెక్కింపు.', 'प्रति मतदारसंघ यादृच्छिकपणे निवडलेल्या 5 मतदान केंद्रांमधून VVPAT स्लिप्सची अनिवार्य शारीरिक मोजणी.', 'ஒரு தொகுதிக்கு 5 தோராயமாக தேர்ந்தெடுக்கப்பட்ட வாக்குச்சாவடிகளில் இருந்து விவிபேட் சீட்டுகளை கட்டாயமாக எண்ணுதல்.', 'મતવિસ્તાર દીઠ 5 અવ્યવસ્થિત રીતે પસંદ કરાયેલા મતદાન મથકોમાંથી VVPAT સ્લિપની ફરજિયાત ભૌતિક ગણતરી.', 'ಪ್ರತಿ ಕ್ಷೇತ್ರಕ್ಕೆ 5 ಯಾದೃಚ್ಛಿಕವಾಗಿ ಆಯ್ಕೆ ಮಾಡಿದ ಮತಗಟ್ಟೆಗಳಿಂದ ವಿವಿಪ್ಯಾಟ್ ಸ್ಲಿಪ್‌ಗಳ ಕಡ್ಡಾಯ ಭೌತಿಕ ಎಣಿಕೆ.'],
  'The RO compiles round-wise results. Any discrepancies are resolved before the final announcement.': ['The RO compiles round-wise results. Any discrepancies are resolved before the final announcement.', 'RO राउंड-वार परिणामों को संकलित करता है। अंतिम घोषणा से पहले किसी भी विसंगतियों को हल किया जाता है।', 'The RO compiles round-wise results. Any discrepancies are resolved before the final announcement.', 'আরও রাউন্ড-ভিত্তিক ফলাফল সংকলন করে। চূড়ান্ত ঘোষণার আগে কোনো অসঙ্গতি সমাধান করা হয়।', 'RO రౌండ్లవారీ ఫలితాలను సంకలనం చేస్తుంది. తుది ప్రకటనకు ముందు ఏవైనా వ్యత్యాసాలు పరిష్కరించబడతాయి.', 'RO फेरीनिहाय निकाल संकलित करते. अंतिम घोषणेपूर्वी कोणत्याही विसंगती दूर केल्या जातात.', 'RO சுற்று வாரியான முடிவுகளை தொகுக்கிறது. இறுதி அறிவிப்புக்கு முன் ஏதேனும் முரண்பாடுகள் தீர்க்கப்படும்.', 'RO રાઉન્ડ-વાર પરિણામોનું સંકલન કરે છે. અંતિમ જાહેરાત પહેલા કોઈપણ વિસંગતતા ઉકેલવામાં આવે છે.', 'RO ಸುತ್ತಿನ-ವಾರು ಫಲಿತಾಂಶಗಳನ್ನು ಕಂಪೈಲ್ ಮಾಡುತ್ತದೆ. ಅಂತಿಮ ಪ್ರಕಟಣೆಯ ಮೊದಲು ಯಾವುದೇ ವ್ಯತ್ಯಾಸಗಳನ್ನು ಪರಿಹರಿಸಲಾಗುತ್ತದೆ.'],
  'The winning candidate is issued a "Certificate of Election" (Form 21C/21D) by the RO.': ['The winning candidate is issued a "Certificate of Election" (Form 21C/21D) by the RO.', 'विजेता उम्मीदवार को RO द्वारा "चुनाव का प्रमाण पत्र" (फॉर्म 21C/21D) जारी किया जाता है।', 'The winning candidate is issued a "Certificate of Election" (Form 21C/21D) by the RO.', 'বিজয়ী প্রার্থীকে RO দ্বারা "নির্বাচনের শংসাপত্র" (ফর্ম 21C/21D) প্রদান করা হয়।', 'గెలిచిన అభ్యర్థికి RO ద్వారా "ఎన్నికల ధృవీకరణ పత్రం" (ఫారమ్ 21C/21D) జారీ చేయబడుతుంది.', 'विजेत्या उमेदवाराला RO कडून "निवडणुकीचे प्रमाणपत्र" (फॉर्म 21C/21D) दिले जाते.', 'வெற்றி பெற்ற வேட்பாளருக்கு RO மூலம் "தேர்தல் சான்றிதழ்" (படிவம் 21C/21D) வழங்கப்படுகிறது.', 'વિજેતા ઉમેદવારને RO દ્વારા "ચૂંટણીનું પ્રમાણપત્ર" (ફોર્મ 21C/21D) આપવામાં આવે છે.', 'ವಿಜೇತ ಅಭ್ಯರ್ಥಿಗೆ RO ನಿಂದ "ಚುನಾವಣಾ ಪ್ರಮಾಣಪತ್ರ" (ಫಾರ್ಮ್ 21C/21D) ನೀಡಲಾಗುತ್ತದೆ.']
};

const translations = {};
languages.forEach(lang => {
  translations[lang] = {};
});

// Load the existing file to append to it
const existingContent = fs.readFileSync('src/context/LanguageContext.tsx', 'utf8');

// Parse the existing translations object (rough string manipulation)
const translationsMatch = existingContent.match(/const translations: Record<Language, Record<string, string>> = (\{[\s\S]*?\});/);

if (translationsMatch) {
  const existingTranslationsObj = eval('(' + translationsMatch[1] + ')');

  // Add the new data keys
  Object.entries(dataKeys).forEach(([key, values]) => {
    languages.forEach((lang, index) => {
      existingTranslationsObj[lang][key] = values[index];
    });
  });

  // Re-stringify and replace
  const newContent = existingContent.replace(
    translationsMatch[0], 
    `const translations: Record<Language, Record<string, string>> = ${JSON.stringify(existingTranslationsObj, null, 2)};`
  );

  fs.writeFileSync('src/context/LanguageContext.tsx', newContent);
  console.log('LanguageContext.tsx updated with data translations!');
} else {
  console.error("Could not find the translations object in the file.");
}
